# Generated by Django 4.2.3 on 2023-07-12 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal', '0002_usuariospacientes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipoServicio_S', models.CharField(max_length=20)),
                ('Precio_S', models.DecimalField(decimal_places=2, max_digits=18)),
                ('Descripcion_S', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Tipo de Servicios',
                'verbose_name_plural': 'Servicios',
                'db_table': 'Servicios',
            },
        ),
    ]
