# Generated by Django 4.2.3 on 2023-07-09 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsuariosMedicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_UM', models.CharField(max_length=45)),
                ('Apellido_UM', models.CharField(max_length=45)),
                ('Email_UM', models.CharField(max_length=45)),
                ('Clave_UM', models.CharField(max_length=45)),
                ('Celular_UM', models.CharField(blank=True, default='Celular_UM', max_length=45)),
                ('Direccion_UM', models.CharField(blank=True, default='Direccion_UM', max_length=100)),
                ('Localidad_UM', models.CharField(blank=True, default='Localidad_UM', max_length=45)),
                ('Dni_UM', models.CharField(blank=True, default='Dni_UM', max_length=8)),
                ('Matricula_UM', models.CharField(blank=True, default='Mat_UM', max_length=8)),
            ],
            options={
                'verbose_name': 'Usuarios Medicos',
                'verbose_name_plural': 'UsuariosMedicos',
                'db_table': 'UsuariosMedicos',
            },
        ),
    ]
