# Generated by Django 4.2.3 on 2023-07-11 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuariosPacientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_UP', models.CharField(max_length=45)),
                ('Apellido_UP', models.CharField(max_length=45)),
                ('Email_UP', models.CharField(max_length=45)),
                ('Clave_UP', models.CharField(max_length=45)),
                ('Celular_UP', models.CharField(blank=True, default='Celular_UP', max_length=45)),
                ('Direccion_UP', models.CharField(blank=True, default='Direccion_UP', max_length=100)),
                ('Localidad_UP', models.CharField(blank=True, default='Localidad_UP', max_length=45)),
                ('Dni_UP', models.CharField(blank=True, default='Dni_UP', max_length=8)),
            ],
            options={
                'verbose_name': 'Usuarios Pacientes',
                'verbose_name_plural': 'UsuariosPacientes',
                'db_table': 'UsuariosPacientes',
            },
        ),
    ]
